import Base
import ./clebsch-laws.bend as Laws
import ./tensor.bend as T

def Laws.cross_contents(x,y,z,u,v,w):
  {==}
def Laws.curl_contents(x,y,z):
  {==}
def Laws.gradient_contents(f):
  {==}
def Laws.curl_fixture_x():
  {==}
def Laws.curl_fixture_y():
  {==}
def Laws.curl_fixture_z():
  {==}
def Laws.two_routes_fixture(axis):
  match axis:
    case T.T{}:
      {==}
    case T.X{}:
      {==}
    case T.Y{}:
      {==}
    case T.Z{}:
      {==}
